theme = 'hugo-theme-relearn'
baseURL = 'https://listertech.uk/'
languageCode = 'en-gb'
title = 'My New Hugo Site'

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
